### ISSUE TITLE
Encryptation logic should be outside of FileEntity

### ISSUE THREAD

**Issue by nminaya** [Raidervz/FileJsonEntity#1]
Encrypt and Decrypt logic should be in another class

**Comment by Raidervz** [comment]
I was thining to be included because I will create one solution for Dart, Java and Objective-C to have the same logic on a single file, easy and not needed to create a full package for the implement the solution just a library and a single file.

**Comment by nminaya** [comment]
I think ecryptation logic should be outside of FileEntity because Single-responsibility principle

**Comment by Raidervz** [comment]
In the new Solution Creation the Encryption is handle in a separated Class
