### ISSUE TITLE
_Entities field seems like it is not useful

### ISSUE THREAD

**Issue by nminaya** [Raidervz/FileJsonEntity#3]
This filed seems like it is not useful to be part of the class. 
https://github.com/Raidervz/FileJsonEntity/blob/a2c4a0c9b6a18ce5bd1a0388285562e6f60e14ff/FileEntity.cs#L18

It is never used, just reassigned.

**Comment by Raidervz** [comment]
Added as a global variable to return Values and debug the code as well the `private T _Entity;` those will be removed once the package will be ready to be usage by every one.

**Comment by nminaya** [comment]
Ok. You should remove those fields before closing this issue

**Comment by Raidervz** [comment]
Removed _Entities and Entity
