### ISSUE TITLE
Method signature of FileJsonEntity.Delete

### ISSUE THREAD

**Issue by nminaya** [Raidervz/FileJsonEntity#5]
https://github.com/Raidervz/FileJsonEntity/blob/c983f246a90c6f84557df7872dae60185c2ecb54/FileEntity.cs#L172

If you see the body of this method, it will always returns true. It never returns false.

This method should be void.

**Comment by Raidervz** [comment]
Added Exception management to the Delete Method

**Comment by nminaya** [comment]
The issue I reported was about the method signature, not about handling exceptions. The Delete method should be void because currently only returns true. 
https://github.com/Raidervz/FileJsonEntity/blob/513899752369872aa6c12ee161f6ace1a96934a6/FileEntity.cs#L203
There is not a scenario where the method returns false. So it does not make sence that the method returns bool if only returns true.

This issue needs to be reopened.

**Comment by Raidervz** [comment]
Lo que sucede es que si hay algun problema retornaria false, o una exeption
